### List internship requests (should be empty initially)
GET http://localhost:3000/api/internship-requests
Accept: application/json

### Create a valid internship request
POST http://localhost:3000/api/internship-requests
Content-Type: application/json

{
  "lastName": "Rossi",
  "firstName": "Mario",
  "email": "mario.rossi@example.com",
  "department": "Engineering",
  "startDate": "2025-11-01",
  "endDate": "2025-12-01",
  "motivation": "Learn about backend development"
}

### Reset internship requests store
DELETE  http://localhost:3000/api/internship-requests/